### ISSUE TITLE
Dependencies directory missing?

### ISSUE THREAD

**Issue by sskspider** [symgenoevolab/SyntenyFinder#1]
Hi, this looks like a great tool from your preprint, congratulations!
I tried to use the code on a Linux machine and have a couple of questions:
1. the "dependencies" directory (including Synteny_functions.py and Bfl folder) in the main directory (as shown by the directory contents figure in the README.md) is missing. I copied the "dependencies" directory from "Bryozoan_Synteny" folder, but got the error "ModuleNotFoundError: No module named 'dependencies.Synteny_functions'"  I have orthofinder, pandas and biopython installed. Am I missing something?
2. How can I use an unpublished genome (chromosomal and annotated) using this pipeline?

Thank you.
Siddharth.

**Comment by ijyliao** [comment]
Dear Siddharth, 

Thank you for your interest in our work! Apologies for the inconvenience; since our work is still a preprint, some of the genome data is not yet available and I had missed uploading the ```dependencies``` folder in the confusion. The directory should now be available. Some of the Bfl files, namely ```Bfl_gene_rows.gtf``` and ```Bfl.fna``` are not available from our repository but can be downloaded from their original source [here](http://fmarletaz.github.io/Resources/). I have reflected these changes in the README but please by all means let me know if you have any additional questions. 

The main pipeline is currently only usable with NCBI-available genomes in order to keep the process streamlined and accessible; however, the jupyter lab version within the directory ```Bryozoan_Synteny``` is considerably more powerful and can work with multiple formats of genome annotations. The file structure is a little different, but the instructions are directly integrated into ```Bryozoan_Synteny/Synteny_main.ipynb```. 

Cheers, 
Isabel

**Comment by sskspider** [comment]
Thanks Isabel, it worked!

**Comment by hhzhao713** [comment]
I have the same problem, can I ask you how to use synteny_main.ipynb?
