### ISSUE TITLE
KeyError: 'XXX_proteomes'，How to use your own data without NCBI accessions number?

### ISSUE THREAD

**Issue by hhzhao713** [symgenoevolab/SyntenyFinder#3]
Importing dependencies
Run name: get_synteny
Accessions: ['GCA_914767715.1', 'GCF_902652985.1']
No alg species provided. Tracing groups from chromosomes of first species listed: GCA_914767715.1
No root directory passed. Will run rooted in current location.
No file location specified for executable orthofinder. Will assume installed.
Threads: 20
           Accession             Organism_Name  Chromosomes
Mme  GCA_914767715.1  Membranipora membranacea           11
Pma  GCF_902652985.1            Pecten maximus           19
Directories built for run...
./ncbi_downloads
Downloading Membranipora membranacea data from accession GCA_914767715.1. 
This may take a while...
Downloading Pecten maximus data from accession GCF_902652985.1. 
This may take a while...
Download complete. Genome GCA_914767715.1 saved to ./ncbi_downloads/Mme/ncbi_dataset.zip.
Incorrect number of proteomes files found for Mme [0]
Incorrect number of features files found for Mme [0]
Download complete. Genome GCF_902652985.1 saved to ./ncbi_downloads/Pma/ncbi_dataset.zip.
Reading proteomes...
Traceback (most recent call last):
  File "/home/.../syntenyfinder/SyntenyFinder-main/SyntenyFinder.py", line 94, in <module>
    SyntenyFinder() 
    ^^^^^^^^^^^^^^^
  File "/home/.../syntenyfinder/SyntenyFinder-main/SyntenyFinder.py", line 86, in SyntenyFinder
    synteny = run_NCBI_Synteny(accessions = accessions, 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../syntenyfinder/SyntenyFinder-main/dependencies/Synteny_functions.py", line 721, in run_NCBI_Synteny
    synteny.parse_proteomes()
  File "/home/.../syntenyfinder/SyntenyFinder-main/dependencies/Synteny_functions.py", line 681, in parse_proteomes
    self.read_proteomes()
  File "/home/.../syntenyfinder/SyntenyFinder-main/dependencies/Synteny_functions.py", line 90, in read_proteomes
    filepath = self.dirs[f'{species}_proteomes']
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Mme_proteomes'

What should I do with this error? Also, I want to use myself for the published data analysis, how should I use Synteny_main.ipynb?

**Comment by ijyliao** [comment]
Hi, this looks like the command line version, which is only able to take the accessions of NCBI annotated genomes. A previous error in the quick start example of the README uses the unannotated genome of _Membranipora membranacea_ (GCA_914767715.1) and would thus result in an error. The example has since been changed to the annotated nemertean species _Lineus longissimus_ to resolve this error. If you would like to run SyntenyFinder with your own data (genomes without a published annotation on NCBI), please download the folder SyntenyFinder_customisable and run Synteny_main.ipynb in Jupyter. For extra guidance, exaqmple_run.ipynb may be a helpful reference on how to run the script.
