### ISSUE TITLE
running using local files

### ISSUE THREAD

**Issue by EvolutionaryGenetics-UB-CEAB** [symgenoevolab/SyntenyFinder#4]
Hi,

It is possible to run the script using local files as stated in the BioRxiv? "It requires three types of file as an input: (1) genome sequence FASTA file; (2) gene positions in the format of a GTF file; and (3) a protein sequence FASTA file." 

If so, how to do it? I can not see this option, only to provide accessions from NCBI.

Thanks!

**Comment by ijyliao** [comment]
Hi, thank you for your interest in our work! To run the script on local files (the version used in the preprint), please download the subdirectory SyntenyFinder_customisable and follow the instructions in SyntenyFinder_main. This version is run in a Jupyter Notebook file rather than on the command line but is much more robust and flexible. For further guidance, example_run.ipynb shows one of our own runs and may be a helpful reference.
